package br.com.amasvisa.arborizacao.arvore.models;

public enum TipoManejo {
    NENHUM,
    MONITORAMENTO,
    PODA_FORMACAO,
    PODA_LIMPEZA,
    PODA_ADEQUACAO,
    PODA_RENOVACAO,
    TRATAMENTO_FITOSANITARIO,
    AMPLIACAO_CANTEIRO,
    TUTORAMENTO,
    AVALIACAO_TRANSPLANTE,
    AVALIACAO_SUPRESSAO,
    COMBATE_PRAGAS,
    TRANSPLANTE,
    EXTRACAO,
    REPOUSO
}
