spring.datasource.url=jdbc:mysql://gateway01.sa-east-1.prod.aws.tidbcloud.com:4000/arborizacao?sslMode=PREFERRED&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=ZzWxWGwXBNFJRnh.root
spring.datasource.password=protLXRJYDTeI5QG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
